# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://anagainaru.github.io'
baseurl: ''
title: 'Workshop on Converged Computing Infrastructure'
description: ''
permalink: pretty
logo: "/images/logo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  Organization: /about/
  Submission: /blog/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
